export const ENDPOINT_NAME_MIN_LENGTH = 3;
export const ENDPOINT_NAME_MAX_LENGTH = 32;
const ENDPOINT_NAME_PATTERN = /^[a-z][a-z0-9-]*$/;

export function createConfig({ name, schemas = [] }) {
  const ids = schemas.filter((id) => typeof id === 'string' && id);
  return { name, schemas: [...new Set(ids)].sort() };
}

// Where the delivery API serves an endpoint, relative to the engine's host.
export const getDeliveryPath = ({ name }) => `/graphql/${name}`;

export const getSchemaEditorHref = ({ origin, org, site }) => `${origin}/apps/schema#/${org}/${site}`;

export function validateEndpointName({ name, existing = [] }) {
  if (!name) return 'An endpoint name is required.';
  if (!ENDPOINT_NAME_PATTERN.test(name)) {
    return 'The endpoint name must start with a letter and contain only lowercase letters, numbers, or hyphens.';
  }
  if (name.length < ENDPOINT_NAME_MIN_LENGTH || name.length > ENDPOINT_NAME_MAX_LENGTH) {
    return `The endpoint name must be ${ENDPOINT_NAME_MIN_LENGTH}–${ENDPOINT_NAME_MAX_LENGTH} characters long.`;
  }
  if (existing.includes(name)) return `An endpoint named "${name}" already exists.`;
  return undefined;
}

export const isValidEndpointName = (name) => typeof name === 'string'
  && !validateEndpointName({ name });

export const serializeConfig = (config) => JSON.stringify(createConfig(config), null, 2);

const parseJson = (text) => {
  try {
    return { json: JSON.parse(text) };
  } catch {
    return { error: 'The endpoint configuration is not valid JSON.' };
  }
};

export function parseConfig({ text, name }) {
  const { json, error } = parseJson(text);
  if (error) return { error };
  if (!json || typeof json !== 'object' || Array.isArray(json)) {
    return { error: 'The endpoint configuration is not an object.' };
  }
  const schemas = Array.isArray(json.schemas) ? json.schemas : [];
  return { config: createConfig({ name, schemas }) };
}

// A draft is the editable form of a config: { name, schemas, isNew }.
export function createDraft({ config, name } = {}) {
  if (!config) return { name, schemas: [], isNew: true };
  return { ...createConfig(config), isNew: false };
}

export const NO_SCHEMAS_MESSAGE = 'At least one Structured Content schema must be selected.';

export function getSaveBlocker({ draft, preview, existing = [] }) {
  if (draft.isNew) {
    const nameError = validateEndpointName({ name: draft.name, existing });
    if (nameError) return nameError;
  }
  if (!draft.schemas.length) return NO_SCHEMAS_MESSAGE;
  if (!preview) return 'The GraphQL schema has not been generated.';
  if (preview.errors.length) return 'Resolve the GraphQL schema errors before saving.';
  return undefined;
}

// Stored SDL artifact: a generated-by header followed by the SDL.

const MARKER = '# @generated by da-nx graphql - do not edit';

export function buildSchemaArtifact({ endpoint, sdl, generatedAt }) {
  return `${MARKER}\n# endpoint: ${endpoint}\n# generatedAt: ${generatedAt}\n\n${sdl}`;
}

export function toSavePayload({ draft, preview, now = new Date() }) {
  const config = createConfig(draft);
  const artifact = buildSchemaArtifact({
    endpoint: config.name,
    sdl: preview.sdl,
    generatedAt: now.toISOString(),
  });
  return { config, artifact };
}
