import { expect } from '@esm-bundle/chai';
import { wrapCodeblock, unwrapCodeblock } from '../../../../nx/blocks/graphql/utils/store.js';
import {
  buildSchemaArtifact, createConfig, isValidEndpointName, parseConfig, serializeConfig,
  validateEndpointName,
} from '../../../../nx/blocks/graphql/utils/endpoint.js';

describe('codeblock', () => {
  it('round-trips text with HTML special characters', () => {
    const text = '"""a <b> & \'c\'"""\ntype A { x: String }';
    const html = wrapCodeblock(text);
    expect(html).to.include('&lt;b&gt; &amp;');
    expect(unwrapCodeblock(html)).to.equal(text);
  });

  it('reads unescaped JSON written by the schema editor', () => {
    expect(unwrapCodeblock('<pre><code>{"a":"b"}</code></pre>')).to.equal('{"a":"b"}');
  });

  it('decodes numeric entities and returns undefined without a code block', () => {
    expect(unwrapCodeblock('<code class="x">&#34;&#x41;</code>')).to.equal('"A');
    expect(unwrapCodeblock('<p>nothing</p>')).to.equal(undefined);
  });
});

describe('config', () => {
  it('normalises schemas to a unique sorted list', () => {
    expect(createConfig({ name: 'a', schemas: ['b'] })).to.deep.equal({ name: 'a', schemas: ['b'] });
    expect(createConfig({ name: 'a', schemas: ['b', 'a', 'b', ''] }))
      .to.deep.equal({ name: 'a', schemas: ['a', 'b'] });
  });

  it('round-trips through serialize and parse, taking the name from the path', () => {
    const text = serializeConfig({ name: 'x', schemas: ['s'] });
    expect(parseConfig({ text, name: 'y' }).config).to.deep.equal({ name: 'y', schemas: ['s'] });
  });

  it('ignores unknown keys', () => {
    const text = '{"description":"d","name":"x","schemas":["b","a"]}';
    expect(parseConfig({ text, name: 'x' }).config).to.deep.equal({ name: 'x', schemas: ['a', 'b'] });
  });

  it('reports invalid configurations', () => {
    expect(parseConfig({ text: '{', name: 'a' }).error).to.be.a('string');
    expect(parseConfig({ text: '[]', name: 'a' }).error).to.be.a('string');
  });

  it('validates endpoint names', () => {
    expect(validateEndpointName({ name: 'marketing-v2' })).to.equal(undefined);
    expect(validateEndpointName({ name: '' })).to.be.a('string');
    expect(validateEndpointName({ name: 'Bad Name' })).to.be.a('string');
    expect(validateEndpointName({ name: '1abc' })).to.be.a('string');
    expect(validateEndpointName({ name: 'a'.repeat(64) })).to.be.a('string');
    expect(validateEndpointName({ name: 'dup', existing: ['dup'] })).to.include('already exists');
    expect(validateEndpointName({ name: 'global' })).to.equal(undefined);
    expect(validateEndpointName({ name: 'ab' })).to.equal('The endpoint name must be 3–32 characters long.');
    expect(validateEndpointName({ name: 'web' })).to.equal(undefined);
    expect(validateEndpointName({ name: 'abcd' })).to.equal(undefined);
    expect(validateEndpointName({ name: 'a'.repeat(32) })).to.equal(undefined);
    expect(validateEndpointName({ name: 'a'.repeat(33) })).to.equal('The endpoint name must be 3–32 characters long.');
    expect([isValidEndpointName('main'), isValidEndpointName('ab'), isValidEndpointName(3)])
      .to.deep.equal([true, false, false]);
  });
});

describe('artifact', () => {
  it('prefixes the SDL with a generated-by header', () => {
    const text = buildSchemaArtifact({ endpoint: 'e', sdl: 'type Query { a: String }', generatedAt: 'now' });
    expect(text.split('\n')).to.deep.equal([
      '# @generated by da-nx graphql - do not edit',
      '# endpoint: e',
      '# generatedAt: now',
      '',
      'type Query { a: String }',
    ]);
  });
});
